/// Used to get and access token given an authorization key
/// accessToken copied into settings.json file
///
/// define URL as a local variable:
baseUrl = https://..........

POST{{baseUrl}}/token
Authorization: Basic {{authorization}}

###

GET{{baseUrl}}/cases
Accept: application/json
Authotization: Bearer {{accessToken}}

###

GET{{baseUrl}}/users
Accept: application/json
Authotization: Bearer {{accessToken}}
